language: generic 
sudo: required
services:
    - docker

before_install:
    - docker build -t ualimam/docker-react -f Dockerfile.dev .

script:
    - docker run ualimam/docker-react npm run test -- --coverage